apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iff-audio

resources:
  - namespace.yaml
  - postgres.yaml
  - pvc-library.yaml
  - api.yaml
  - web.yaml

images:
  - name: iff-api
    newName: iff-api
    newTag: local
  - name: iff-web
    newName: iff-web
    newTag: local
